dllp/config/routes.rb
Rails.application.routes.draw do

  get 'learn/index'

  get 'learn/validate'

  root 'authentications#index'

  get   'login' => 'authentications#login'
  get   'signup' => 'authentications#register'
  get   'forgotpassword' => 'authentications#forgot'
  get   'logout' => 'authentications#logout'
  post  'login' => 'authentications#do_login'
  post  'signup' => 'authentications#do_signup'
  post  'forgotpassword' => 'authentications#do_forgot'

  get 'dashboard' => 'dashboard#index'

  get 'progress' => 'progress#index'

  get  'learn' => 'learn#index'
  get  'learn/unanswered' => 'learn#unanswered'
  get  'learn/incorrect' => 'learn#incorrect'
  post 'learn' => 'learn#validate'

  get 'exam' => 'exam#index'
  post 'exam' => 'exam#validate'
  get 'exam/result/:id' => 'exam#result'

  get 'user' => 'user#edit'
  post 'user' => 'user#update'

end

dllp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DLLP - <%= yield :title %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag params[:controller] %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="container">
  <!-- Header start -->
  <header class="navbar" role="navigation">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse"
              data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span> <span
      class="icon-bar"></span> <span class="icon-bar"></span> <span
      class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">&nbsp;</a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse"
         role="navigation">

      <ul class="nav navbar-nav">
        <li><%= image_tag 'logo.png', {height: '45px'} %></li>
        <li><a href="<%= dashboard_path %>"><span
        class="glyphicon glyphicon-stats" aria-hidden="true"></span>
          Overview</a></li>
        <li><a href="<%= learn_path %>"><i class="icon-beaker"> </i>
          Smart Practice</a></li>
        <li><a href="<%= progress_path %>"><span
        class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
          My Progress</a></li>
        <li><a href="<%= exam_path %>"><i class="icon-dashboard"> </i>
          Exam</a></li>
      </ul>

      <!-- Mini navigation start -->
      <ul class="nav navbar-nav navbar-right hidden-xs hidden-sm ">
        <li><a title="" data-original-title="" href="<%= user_path %>"><i
        class="icon-gears"></i> Settings</a></li>
        <li><%= link_to raw('<i class="icon-signout"></i> Logout'), controller: 'authentications', action: 'logout' %></li>
      </ul>
      <!-- Mini navigation end -->

    </nav>
  </header>
  <!-- Header end -->
  <div class="row">

  </div>

  <!-- Row start -->
  <div id="result">
    <%= yield %>
  </div>
  <!-- Row end -->

  <div class="row">
    <div id="error-message" class="alert alert-danger">Error message</div>
    <div id="info-message" class="alert alert-info">Loading, please wait.</div>
    <div id="success-message" class="alert alert-success">Error message</div>
  </div>

</div>
</body>
</html>

dllp/app/views/layouts/authentications.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DLLP - Login</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag params[:controller] %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= yield %>

</body>
</html>